group 'org.wikilift.flutter_msal_plus'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.4.0'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1'
        }
    }
}

apply plugin: 'com.android.library'

android {
    namespace "org.wikilift.flutter_msal_plus"

    compileSdk = 36

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 36
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    buildFeatures {
        buildConfig = false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }


    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.microsoft.identity.client:msal:4.0.2'
    testImplementation 'junit:junit:4.13.2'
}
kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}
